export const posts = [
    {
      id: 1,
      title: "5 Premium Theme for React",
      img: "https://images.pexels.com/photos/7963572/pexels-photo-7963572.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea?",
      longDesc:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptas, animi. Quia, in libero quam a placeat laudantium aliquid? Suscipit non fuga inventore rerum? Dolor assumenda atque vel soluta, dolore, temporibus nemo natus cupiditate accusamus fuga, incidunt commodi molestias ea reprehenderit sequi. Ab consequuntur sint deserunt saepe rerum autem labore alias eius ipsum? Ea, a ipsa nulla sed fuga sint nihil obcaecati optio commodi explicabo eos reiciendis deserunt esse ex, est officiis architecto non quos odit earum facere rem numquam consequatur! Numquam veritatis inventore, ullam veniam natus quisquam iste commodi quaerat minima illum alias quibusdam dolorum error. Cumque eaque quas reprehenderit aliquid, exercitationem minus aperiam, inventore nesciunt et ex culpa similique odit eveniet sequi recusandae aliquam soluta aspernatur dolor! Ullam asperiores architecto repudiandae corrupti necessitatibus tempora corporis totam placeat consequatur vel. Sit tenetur odio ullam assumenda distinctio molestiae, quo fugit voluptatum veritatis dolor recusandae quia facilis nulla numquam incidunt rem nobis amet placeat quam totam aliquid autem vitae ab modi! Quidem molestias dolor hic quibusdam fugit eius officiis vero illum ipsam, voluptatum blanditiis. Harum, laudantium amet? Harum impedit quia quibusdam tenetur doloremque architecto animi! Voluptates quod aliquam magni a ut officiis perferendis modi aperiam. Quod hic aperiam, suscipit assumenda accusamus obcaecati.",
    },
    {
      id: 2,
      title: "How to Animate Elements?",
      img: "https://images.pexels.com/photos/1742370/pexels-photo-1742370.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea?",
      longDesc:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptas, animi. Quia, in libero quam a placeat laudantium aliquid? Suscipit non fuga inventore rerum? Dolor assumenda atque vel soluta, dolore, temporibus nemo natus cupiditate accusamus fuga, incidunt commodi molestias ea reprehenderit sequi. Ab consequuntur sint deserunt saepe rerum autem labore alias eius ipsum? Ea, a ipsa nulla sed fuga sint nihil obcaecati optio commodi explicabo eos reiciendis deserunt esse ex, est officiis architecto non quos odit earum facere rem numquam consequatur! Numquam veritatis inventore, ullam veniam natus quisquam iste commodi quaerat minima illum alias quibusdam dolorum error. Cumque eaque quas reprehenderit aliquid, exercitationem minus aperiam, inventore nesciunt et ex culpa similique odit eveniet sequi recusandae aliquam soluta aspernatur dolor! Ullam asperiores architecto repudiandae corrupti necessitatibus tempora corporis totam placeat consequatur vel. Sit tenetur odio ullam assumenda distinctio molestiae, quo fugit voluptatum veritatis dolor recusandae quia facilis nulla numquam incidunt rem nobis amet placeat quam totam aliquid autem vitae ab modi! Quidem molestias dolor hic quibusdam fugit eius officiis vero illum ipsam, voluptatum blanditiis. Harum, laudantium amet? Harum impedit quia quibusdam tenetur doloremque architecto animi! Voluptates quod aliquam magni a ut officiis perferendis modi aperiam. Quod hic aperiam, suscipit assumenda accusamus obcaecati.",
    },
    {
      id: 3,
      title: "learn JS in 30 days",
      img: "https://images.pexels.com/photos/1161547/pexels-photo-1161547.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea?",
      longDesc:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptas, animi. Quia, in libero quam a placeat laudantium aliquid? Suscipit non fuga inventore rerum? Dolor assumenda atque vel soluta, dolore, temporibus nemo natus cupiditate accusamus fuga, incidunt commodi molestias ea reprehenderit sequi. Ab consequuntur sint deserunt saepe rerum autem labore alias eius ipsum? Ea, a ipsa nulla sed fuga sint nihil obcaecati optio commodi explicabo eos reiciendis deserunt esse ex, est officiis architecto non quos odit earum facere rem numquam consequatur! Numquam veritatis inventore, ullam veniam natus quisquam iste commodi quaerat minima illum alias quibusdam dolorum error. Cumque eaque quas reprehenderit aliquid, exercitationem minus aperiam, inventore nesciunt et ex culpa similique odit eveniet sequi recusandae aliquam soluta aspernatur dolor! Ullam asperiores architecto repudiandae corrupti necessitatibus tempora corporis totam placeat consequatur vel. Sit tenetur odio ullam assumenda distinctio molestiae, quo fugit voluptatum veritatis dolor recusandae quia facilis nulla numquam incidunt rem nobis amet placeat quam totam aliquid autem vitae ab modi! Quidem molestias dolor hic quibusdam fugit eius officiis vero illum ipsam, voluptatum blanditiis. Harum, laudantium amet? Harum impedit quia quibusdam tenetur doloremque architecto animi! Voluptates quod aliquam magni a ut officiis perferendis modi aperiam. Quod hic aperiam, suscipit assumenda accusamus obcaecati.",
    },
  ];